name: Release

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Frontend
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Cache Backend
        uses: Swatinem/rust-cache@v1.2.0
        with:
          working-directory: ./app/src-tauri

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Setup tauri
        run: cargo install tauri-cli --version ^1.0.0-beta

      - name: Install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Build Frontend
        run: pnpm i && pnpm build
        working-directory: ./app/src-ui

      - name: Lint Backend
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path ./app/src-tauri/Cargo.toml

      - name: Build Tauri
        run: cargo tauri build
        working-directory: ./app/

      - name: Prerelease
        uses: softprops/action-gh-release@v1
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          files: ./app/src-tauri/target/release/bundle/**/TicTacToe*.*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./app/src-tauri/target/release/bundle/**/TicTacToe*.*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
